name: Package and Release

on: [pull_request]
#  workflow_dispatch:
#    inputs:
#      release_version:
#        description: 'Version to be released'
#        required: true


jobs:
  Create_GitHub_release:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install stuff
      run: |
        set -e
        curl -o  pyoxidizer.zip -L "https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.17/pyoxidizer-0.17.0-linux_x86_64.zip"
        unzip pyoxidizer.zip
        chmod +x ./pyoxidizer

    - name: Create Executable
      run: |
        set -e
        ./pyoxidizer build --release

        export Q_EXECUTABLE=./build/x86_64-unknown-linux-gnu/release/install/q

        seq 1 100 | $Q_EXECUTABLE -c 1 "select sum(c1),count(*) from -"

        mkdir -p artifacts/linux/
        cp $Q_EXECUTABLE artifacts/linux/

    - name: Upload Artifact - TBD Move to the end
      uses: actions/upload-artifact@v2
      with:
        - name: artifacts
        - path: artifacts/
    - name: Install Python for Testing
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.12'
        architecture: 'x64'
    - name: Prepare Testing
      run: |
        pip3 install -r test-requirements.txt

        Q_EXECUTABLE=../build/x86_64-unknown-linux-gnu/release/install/q test/test-all

#    - name: Create release for ${{ github.event.client_payload.ReleaseBranchName }}
#      uses: actions/create-release@v1.1.1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ github.event.client_payload.ReleaseBranchName }}
#        release_name: ${{ github.event.client_payload.ReleaseTitle }}
#        body: ${{ github.event.client_payload.ReleaseBody }}
#        prerelease: ${{ github.event.client_payload.Prerelease }}
#        commitish: ${{ github.event.client_payload.Commitish }}