
name: Package

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
