name: Package and Release

on: [pull_request]
#  workflow_dispatch:
#    inputs:
#      release_version:
#        description: 'Version to be released'
#        required: true

jobs:
  create-man:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'  # Perhaps 2.4.1?
    - name: Create man page
      run: |
        set -x -e
        gem install ronn

        ronn doc/USAGE.markdown
        # Must be gzipped, otherwise debian does not install it
        gzip doc/USAGE
    - name: Upload man page
      uses: actions/upload-artifact@v1.0.0
      with:
        name: q-man-page
        path: doc/USAGE.gz

  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache pyox
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pyoxidizer
        key: ${{ runner.os }}-pyox
    - name: Install pyoxidizer
      run: |
        set -e -x

        sudo apt-get update
        sudo apt-get install -y zip sqlite3 rpm

        curl -o pyoxidizer.zip -L "https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.17/pyoxidizer-0.17.0-linux_x86_64.zip"
        unzip pyoxidizer.zip
        chmod +x ./pyoxidizer
    - name: Create Q Executable - Linux
      run: |
        set -e -x

        ./pyoxidizer build --release

        export Q_EXECUTABLE=./build/x86_64-unknown-linux-gnu/release/install/q
        chmod 755 $Q_EXECUTABLE

        seq 1 100 | $Q_EXECUTABLE -c 1 "select sum(c1),count(*) from -" -S test.sqlite

        mkdir -p artifacts/linux/
        cp $Q_EXECUTABLE artifacts/linux/
    - name: Upload Linux Executable
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux-q
        path: artifacts/linux/q

  test-linux:
    needs: build-linux
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python for Testing
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.12'
        architecture: 'x64'
    - name: Prepare Testing
      run: |
        set -e -x

        pip3 install -r test-requirements.txt
    - name: Download Linux Executable
      uses: actions/download-artifact@v2
      with:
        name: linux-q
        path: artifacts/linux/q
    - name: Run Tests on Resulting Executable
      run: |
        Q_EXECUTABLE=artifacts/linux/q bash -x test/test-all

  package-linux-deb:
    needs: [test-linux, create-man]
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Downoad man page
      uses: actions/download-artifact@v2
      with:
        name: q-man-page
        path: doc/USAGE.gz
    - name: Download Linux Executable
      uses: actions/download-artifact@v2
      with:
        name: linux-q
        path: artifacts/linux/q
    - name: Build DEB Package
      run: |
        set -e -x

        chmod 755 artifacts/linux/q

        cp dist/fpm-config ~/.fpm
        fpm -s dir -t deb --deb-use-file-permissions -p artifacts/linux/q-text-as-data-2.0.20-1.x86_64.deb --version 2.0.20 artifacts/linux/q=/usr/bin/q doc/USAGE.gz=/usr/share/man/man1/q.1.gz
    - name: Test DEB Package Installation
      continue-on-error: true
      run: ./dist/test-using-deb.sh artifacts/linux/q-text-as-data-2.0.20-1.x86_64.deb

  package-linux-rpm:
    needs: [test-linux, create-man]
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Downoad man page
      uses: actions/download-artifact@v2
      with:
        name: q-man-page
        path: doc/USAGE.gz
    - name: Download Linux Executable
      uses: actions/download-artifact@v2
      with:
        name: linux-q
        path: artifacts/linux/q
    - name: Build RPM Package
      run: |
        set -e -x

        chmod 755 artifacts/linux/q

        cp dist/fpm-config ~/.fpm
        fpm -s dir -t rpm --rpm-use-file-permissions -p artifacts/linux/q-text-as-data-2.0.20.x86_64.rpm --version 2.0.20 artifacts/linux/q=/usr/bin/q doc/USAGE.gz=/usr/share/man/man1/q.1.gz
    - name: Retest using RPM
      continue-on-error: true
      run: ./dist/test-using-rpm.sh artifacts/linux/q-text-as-data-2.0.20.x86_64.rpm

  build-mac:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache pyox
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pyoxidizer
        key: ${{ runner.os }}-pyox
    - name: Install pyoxidizer
      run: |
        set -e -x

        curl -o  pyoxidizer.zip -L "https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.17/pyoxidizer-0.17.0-macos-universal.zip"
        unzip pyoxidizer.zip
        mv macos-universal/pyoxidizer ./pyoxidizer

        chmod +x ./pyoxidizer
    - name: Create Q Executable - Mac
      run: |
        set -e -x

        ./pyoxidizer build --release

        export Q_EXECUTABLE=./build/x86_64-apple-darwin/release/install/q
        chmod 755 $Q_EXECUTABLE

        seq 1 100 | $Q_EXECUTABLE -c 1 "select sum(c1),count(*) from -" -S test.sqlite

        mkdir -p artifacts/macos/
        cp $Q_EXECUTABLE artifacts/macos/
    - name: Upload MacOS Executable
      uses: actions/upload-artifact@v1.0.0
      with:
        name: macos-q
        path: artifacts/macos/q

  test-mac:
    needs: build-mac
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python for Testing
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.12'
        architecture: 'x64'
    - name: Prepare Testing
      run: |
        set -e -x

        pip3 install -r test-requirements.txt
    - name: Download MacOS Executable
      uses: actions/download-artifact@v2
      with:
        name: macos-q
        path: artifacts/macos/q
    - name: Run Tests on Resulting Executable
      run: |
        Q_EXECUTABLE=artifacts/macos/q bash -x test/test-all

  build-and-package-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install MSVC build tools
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64'
    - name: Install pyoxidizer
      shell: bash
      run: |
        set -x -e

        python3 -V
        pip3 -V

        pip3 install pyoxidizer
    - name: Create Q Executable - Windows
      shell: bash
      run: |
        set -e -x

        ./pyoxidizer build --release

        export Q_EXECUTABLE=./build/x86_64-pc-windows-msvc/release/install/q
        chmod 755 $Q_EXECUTABLE

        seq 1 100 | $Q_EXECUTABLE -c 1 "select sum(c1),count(*) from -" -S test.sqlite

        mkdir -p artifacts/windows/
        cp $Q_EXECUTABLE artifacts/windows/
    - name: Upload Linux Executable
      uses: actions/upload-artifact@v1.0.0
      with:
        name: win-q
        path: artifacts/win/q
